### ISSUE TITLE
Get rid of Tilecache

### ISSUE THREAD

**Issue by leplatrem** [makinacorpus/Geotrek#1184]
I might be out of Geotrek scope : Geotrek should just take a list of layers URL like Geotrek-rando.

Pros:

* Initially it was developped to proxify WMS of national parks
* It adds some complexity in the deployment scripts
* It is not required since IGN provides WMTS for most layers
* It would allow anyone to add as many layers as desired (now only possible through advanced configuration)

Cons:

* Some structures (e.g. AlpiMaritime) might not have access to detailed map background tiles
* Using EPSG:3857 in the user interface might be problematic for some regions of the world (*hum hum*)

![selection_407](https://cloud.githubusercontent.com/assets/546692/4109613/71e7877a-31e7-11e4-96e9-f069bc4cb5aa.png)
( *screenshot of Grands Causses IGN CADASTRE layer in Geotrek admin* )

**Comment by gutard** [comment]
Geoportail offers Lambert 93 WMTS service. I don't know if it is new since this bug was opened. Anyway I'm not convinced that offset problems with cadastre comes from the projection of tiles.

@camillemonchicourt, do you still use tilecache for PNE or Mercantour/AlpiMaritime ? I think if we need a tilecache for AlpiMaritime we should deploy it separatly from Geotrek.

**Comment by camillemonchicourt** [comment]
Yes indeed, offset problems with CADASTRE is due to the fact that this is not the same referentiel as other IGN maps (Scan 25...).

We dont use TileCache anymore. We use IGN Geoportail API as other users.
https://groups.google.com/forum/#!topic/geotrek-fr/pW6mIhUAOno
And it works very well ! :-)

**Comment by gutard** [comment]
Closed by #1585
